export {
  BrowserRouter,
  MemoryRouter,
  Switch,
  Route,
  Link,
  useRouteMatch,
  useParams,
  useHistory,
  useLocation,
  generatePath,
  Prompt,
  RedirectProps,
  Redirect,
  RouteChildrenProps,
  RouteComponentProps,
  RouteProps,
  Router,
  StaticRouter,
  SwitchProps,
  match,
  matchPath,
  withRouter,
  RouterChildContext,
} from 'react-router-dom';
